Repository HackYourFuture-CPH/FP-class11, pull requests merged in 2020-04, with the labels that each got.

#103 Endpoint for getting all crops
  src/server/api/controllers/crops.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/crops.router.js
  src/server/config/swagger.json
Labels: documentation

#195 resolved errors updated delete-specific-batch
  src/server/api/routes/api-router.js
  src/server/config/swagger.json
Labels: backend

#179 Add default user sign-in; protect routes; update token documentation
  .env.example
  README.md
  firebase-token.md
  package.json
  src/client/App.js
  src/client/helpers/signInAsDefaultUser.js
  src/server/api/routes/batches.router.js
  src/server/api/routes/crop-stage-default-values.router.js
  src/server/api/routes/crop-stages.router.js
  src/server/api/routes/sensor-reading.router.js
  src/server/config/swagger.json
  webpack.config.js
Labels: documentation, frontend

#193 Feature/delete specfic batch endpoint
  package-lock.json
  package.json
  src/server/api/routes/api-router.js
  src/server/api/routes/delete-specfic-batch.router.js
  src/server/api/routes/delete-specific-batch.router.js
Labels: documentation

#192 feature/refactoring-confirm-delete-batch
  src/client/components/delete-confim/delete-confirm.stories.js
  src/client/components/delete-confim/modal-list-style.css
  src/client/components/delete-confim/modal-list.component.js
Labels: storybook

#184 Feature/swagger autodocs
  package.json
  src/server/api/controllers/create-batch.controller.js
  src/server/api/routes/api-router.js
  src/server/api/routes/batch-default-values.router.js
  src/server/api/routes/batches.router.js
  src/server/api/routes/create-batch.router.js
  src/server/api/routes/create-crop.router.js
  src/server/api/routes/crop-stage-default-values.router.js
  src/server/api/routes/crop-stages.router.js
  src/server/api/routes/modules.router.js
  src/server/api/routes/sensor-reading.router.js
  src/server/api/routes/users.router.js
  src/server/config/swagger.json
Labels: documentation

#185 view-batch-detail-page added with story and style
  src/client/App.js
  src/client/components/add-batch-page/add-batch-page.component.js
  src/client/components/chart-detail-page-layout/chart-detail-page.component.js
  src/client/components/edit-batch-image/edit-batch-image.component.js
  src/client/components/edit-batch-image/edit-batch-image.style.css
  src/client/components/form-view-batch-details/form-view-batch-details.component.js
  src/client/components/form-view-batch-details/form-view-batch-details.stories.js
  src/client/components/form-view-batch-details/form-view-batch-details.style.css
  src/client/components/input-output-field/Input-text.stories.js
  src/client/components/input-output-field/input-date.css
  src/client/components/input-output-field/input-date.stories.js
  src/client/components/input-output-field/input-output-date.component.js
  src/client/components/input-output-field/input-output-text.component.js
  src/client/components/input-output-field/input-text.css
  src/client/components/view-batch-detail/view-batch-details.component.js
  src/client/components/view-batch-detail/view-batch-details.stories.js
  src/client/components/view-batch-detail/view-batch-details.style.css
  src/client/containers/dashboard-page/dashboard-page.container.js
  src/client/containers/view-batch-detail-page/view-batch-detail-page.component.js
  src/client/containers/view-batch-detail-page/view-batch-detail-page.stories.js
  src/client/containers/view-batch-detail-page/view-batch-detail-page.style.css
  src/server/api/controllers/crops.controller.js
Labels: frontend

#223 Fix/chart details
  src/client/components/chart-data-buttons/chartbar-buttons/chart-data-button.component.js
  src/client/components/chart-data-buttons/chartbar-buttons/chart-data-button.style.css
  src/client/components/chart-detail-page-layout/chart-detail-page.component.js
  src/client/components/chart-detail-page-layout/chart-detail-page.css
  src/client/components/dashboard-items/dashboard-items.component.js
  src/client/components/dashboard-items/dashboard-items.style.css
  src/client/components/detail-chart/detail-chart.component.js
  src/client/components/detail-chart/detail-chart.stories.js
  src/client/components/detail-chart/detail-chart.style.css
  src/client/components/side-navigation/sidebar.component.js
  src/client/components/update-date-range/update-date-range.component.js
  src/client/containers/chart-detail-page/chart-detail-page.container.js
Labels: frontend
